### PR TITLE
Fixed bug where player would get controlled by another player in endgame

### LINKED ISSUE #53: Player not spawning
Sometimes when switching levels a player will not be spawned

### PR DESCRIPTION
**Pull request by Peter-JanGootzen**
# Description

This fixes a bug where when you would hold a player whilst the last level ended and the endgame scene started, the player you held would still be a child(so you would semi control that other player because of relative position of a child). Fixes #53.

# How can this be tested?
Try to reproduce the bug on master and check whether isn't reproducible in this PR.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Code is const correct

### CODE REVIEW

**Review by MarkMeer — APPROVED** [review]
Tested it on this branch and master and works well

**Review by LuukSantegoeds — COMMENTED** [review]
Can you maybe also this the grandparents exception in this branch? It is pretty related

**Comment by JanSchollaert** [comment]
And remove pickup component on revive of player? Also related xd

**Comment by Peter-JanGootzen** [comment]
Work in Progressing this because it seems to introduce a bug where the dead player always disappears in the second level.

**Review by MarkMeer — APPROVED** [review]
Not sure what exactly had to be reviewed, the following things were tested and acted as expected;
- Cannot pickup alive players to eliminate the following issues;
    - Grandparents exception
    - Put someone in the end game level in the podium
- In the end screen, the child is no longer staying the parent's child from the scene it came from.

**Review by Bram-Boris — APPROVED** [review]

**Pull request merged**
