### PR TITLE
Name picker in lobby

### PR DESCRIPTION
**Pull request by LuukSantegoeds**
# Description
You can pick a name when in the lobby which will be used to track stats. These names are loaded from a JSON file where the user can change the names if the player would like to.

_I also increased the Start Game button width to fit the text but that is not included in the screenshots._

## Screenshot(s)
image
image
image
image
image

# How can this be tested?
Test it like you and 3 friends would try to play the game and try breaking it by navigating menu's etc.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged and published in downstream modules
_I have no engine changes Bram_
- [x] Included 1 or more screenshots
- [x] Code is const correct

### CODE REVIEW

**Review by MarkMeer — APPROVED** [review]
Nicely done, completely agree with @Peter-JanGootzen that it improves the lobby a lot when the arrows are gone. Well made 👍

**Review by Peter-JanGootzen — CHANGES_REQUESTED** [review]
Please update the screenshots... :-1:

**Comment by JanSchollaert** [comment]
yeet

**Review by Peter-JanGootzen — APPROVED** [review]
Nice that you solved it with Alpha. :tophat:s off

**Pull request merged**
