### PR TITLE
Level editor

### PR DESCRIPTION
**Pull request by MarkMeer**
# Description
Being able to easily 'debug' the scene that is in assets/debugger/ in the file level.json. When an error occurs in the json or the file cannot be loaded, an error will be thrown.

##### Pause PR
_- [https://github.com/Brick-Studios/BrickEngine/pull/62](url)_ ✅ 
_- [https://github.com/Brick-Studios/BeastArena/pull/50](url)_ ✅ 

##### Engine
_- [https://github.com/Brick-Studios/BrickEngine/pull/65](url)

## Screenshot(s)
Screenshot 2019-12-11 at 09 27 13

# How can this be tested?
- [ ] The debugger shows an error when the file is not correct.
- [ ] The debugger shows an error when the file is not present.
- [ ] By pressing F5 a (valid) json level is re-loaded.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged and published in downstream modules
- [X] Included 1 or more screenshots
- [X] Code is const correct

### CODE REVIEW

**Review by LuukSantegoeds — APPROVED** [review]
**Very nice feature!**

**Review by JanSchollaert — CHANGES_REQUESTED** [review]
Smoll requests:

Can all buttons in main menu be moved up slightly? Exit game almost falls off the screen lmao
Maybe change the button name to "level editor" instead of "debug level"?

Other than that 🔥

**Comment by MarkMeer** [comment]
About the text on the button, Peter-Jan and I decided to make this; Debug level as it is not really a level editor @JanSchollaert. I will push the buttons a little bit higher. Will try what feels fine, without making them ‘fly’ in the sky.

**Review by JanSchollaert — APPROVED** [review]
lit

**Review by JanSchollaert — CHANGES_REQUESTED** [review]
Changes that I will explain later (this is so we cant merge it)

**Review by JanSchollaert — APPROVED** [review]

**Pull request merged**
