### PR TITLE
Updated level template to comply with new level making guide

### PR DESCRIPTION
**Pull request by LuukSantegoeds**
https://docs.google.com/document/d/1jOp_KqehdGv4mI5aw_IoK3stonrSMT_TAQbnyYL11VQ/edit#

### CODE REVIEW

**Review by JanSchollaert — APPROVED** [review]
Left some comments on the drive doc but this looks good

**Comment by LuukSantegoeds** [comment]
@JanSchollaert thanks, I processed the feedback on the document

**Review by JanSchollaert — CHANGES_REQUESTED** [review]
Template must have 4 player spawns otherwise the template doesnt even build

**Comment by LuukSantegoeds** [comment]
@JanSchollaert I know, but it is just a prove of concept. The manual states that a level needs 4 spawns

**Review by JanSchollaert — APPROVED** [review]

**Review by Peter-JanGootzen — APPROVED** [review]
:monkey_face:

**Pull request merged**
