### PR TITLE
LGTM pipeline testing

### PR DESCRIPTION
**Pull request by Peter-JanGootzen**

### CODE REVIEW

**Comment by robertbrignull** [comment]
(disclaimer, I work on LGTM)
I think the problem that LGTM is having when analysing this pull request is the relative path of the [`../BrickEngine.git` submodule](https://github.com/Brick-Studios/BeastArena/blob/master/.gitmodules). We'll work on fixing this but for now I think it'll work if you change the submodule to point at `https://github.com/Brick-Studios/BrickEngine`.

**Comment by Peter-JanGootzen** [comment]
> (disclaimer, I work on LGTM)
> I think the problem that LGTM is having when analysing this pull request is the relative path of the [`../BrickEngine.git` submodule](https://github.com/Brick-Studios/BeastArena/blob/master/.gitmodules). We'll work on fixing this but for now I think it'll work if you change the submodule to point at `https://github.com/Brick-Studios/BrickEngine`.

That must be the reason why our other repository [BrickEngine](https://github.com/Brick-Studios/BrickEngine) does work fine on LGTM. We are using the relative git paths because our team has both HTTPS and SSH users and this was the workaround we found. We'll look into another workaround or we'll have to wait for the fix on your side.

Thanks a lot for the comment and heads up. We were quite astonished that the error got automatically reported and that someone actually looked at it.

**Comment by robertbrignull** [comment]
> We'll look into another workaround or we'll have to wait for the fix on your side.

The fix is actually done now, so it should be deployed to lgtm.com early next week.

> Thanks a lot for the comment and heads up. We were quite astonished that the error got automatically reported and that someone actually looked at it.

That's ok. We monitor failures on pull requests and try to keep everything running smoothly.

**Comment by Peter-JanGootzen** [comment]
@robertbrignull It works, thanks a lot!

**Pull request merged**
