### PR TITLE
Animations fix

### PR DESCRIPTION
**Pull request by JanSchollaert**
# Description

You can now actually create new animations xD
(Also added it to the systems so it can be used in pause)

# How can this be tested?
Test with https://github.com/Brick-Studios/BrickEngine/pull/66
Do you see the tree animating?
Does it stop animating when you pause?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Included 1 or more screenshots
- [x] Code is const correct

### CODE REVIEW

**Review by Peter-JanGootzen — APPROVED** [review]
:fire:

**Review by Peter-JanGootzen — CHANGES_REQUESTED** [review]
Could you maybe fix this as well? https://github.com/Brick-Studios/BeastArena/issues/65
This is fixable my moving animations to it's own system, so that it can be disabled in the Pause game state

**Comment by JanSchollaert** [comment]
> Could you maybe fix this as well? #65
> This is fixable my moving animations to it's own system, so that it can be disabled in the Pause game state

yesss

**Review by MarkMeer — APPROVED** [review]
Nice 🔥

**Review by Peter-JanGootzen — COMMENTED** [review]
Is it me or is the animation now reversed?

**Comment by JanSchollaert** [comment]
> Is it me or is the animation now reversed?

Put your laptop upside down ez fix

**Review by Peter-JanGootzen — APPROVED** [review]
:fish:

**Comment by Peter-JanGootzen** [comment]
> Is it me or is the animation now reversed?

This problem has magically disappeared on its own.

**Pull request merged**
